### ISSUE TITLE
Multiple IPs  for env ALLOWED_NETWORKS

### ISSUE THREAD

**Issue by asalisaf** [kalaksi/docker-tinyproxy#1]
Hello,
Is there a way to pass multiple IP addresses using ALLOWED_NETWORKS environment variable?

**Comment by kalaksi** [comment]
Hi, yes there is. Just separate the IPs or networks by space. It's mentioned in a comment in the Dockerfile.

**Comment by AnusLab** [comment]
how its possible to use basic auth, with set allowed_networks to all?

**Comment by kalaksi** [comment]
@Ratte443 just don't set ALLOWED_NETWORKS at all? By default, tinyproxy allows all unless you set Allow or Deny (https://linux.die.net/man/5/tinyproxy.conf search for "allow,").
I'll add a comment in the example docker-compose.yml since may not be obvious.
