### ISSUE TITLE
log file on perisitent volume

### ISSUE THREAD

**Issue by perler** [kalaksi/docker-tinyproxy#11]
is there a way to get the log file onto a peristent volume?

**Comment by kalaksi** [comment]
Nothing simple at the moment. You could use custom tinyproxy.conf so you can control the `LogFile` option or somehow configure logging on docker level (or journald/syslog). I'll probably  add an env variable for `LogFile` at some point.

**Comment by perler** [comment]
ok, can I simply link the tinyproxy.conf outside the container with docker-compose and edit it?

**Comment by kalaksi** [comment]
Yes, with bind mounts. See: https://github.com/kalaksi/docker-tinyproxy#configuration
