### ISSUE TITLE
tinyproxy 1.11.2

### ISSUE THREAD

**Issue by onyn** [kalaksi/docker-tinyproxy#13]
Recently tinyproxy releases verfsion 1.11.2 which closes critical security issue. Please publish updated version of docker image.

It's already published in [alpine repo](https://pkgs.alpinelinux.org/package/v3.19/main/x86_64/tinyproxy). Debian also published it in [trixie (testing)](https://packages.debian.org/trixie/tinyproxy), so base image should be changed.

**Comment by kalaksi** [comment]
Thanks for the heads up. I'm just publishing it.
