### ISSUE TITLE
linux/arm64 platform support

### ISSUE THREAD

**Issue by bfg100k** [kalaksi/docker-tinyproxy#14]
Hi,

Thanks for creating this. Any chance you can add platform support for linux/arm64? I'm trying to run this on my Raspberry Pi 3. Cheers.

**Comment by kalaksi** [comment]
Yeah, that would be useful. I'll look into that.

**Comment by kalaksi** [comment]
"latest" should now have a multiarch image with arm64. Could you try it out for me? I don't have a rpi at hand right now.
