### ISSUE TITLE
Allow connection from all IPs

### ISSUE THREAD

**Issue by chaos-baum** [kalaksi/docker-tinyproxy#16]
When not setting a specific ALLOWED_NETWORKS then the standard conf values are used which only allow access from local IPs.
That is because the default conf contains this:
```
Allow 127.0.0.1
Allow ::1
```

To fix that it would be nice if there was a ENV option is like ALLOW_ALL_NETWORKS and if that is set to "yes" then a Allow 0.0.0.0/0 or something should be added. 

Would be a nice addition.

**Comment by kalaksi** [comment]
Oh, it's supposed to work so that leaving it empty allows all networks. I'll look into it.

**Comment by kalaksi** [comment]
This is now fixed. Thanks for reporting!
