### ISSUE TITLE
Allow overriding Listen & Port via env variable

### ISSUE THREAD

**Issue by aaabramov** [kalaksi/docker-tinyproxy#17]
As far as I [can see](https://github.com/kalaksi/docker-tinyproxy/blob/master/Dockerfile.alpine#L48-L57), it is not possible to override either `Listen` or `Port` options.

I will be happy to contribute this if @kalaksi is fine with this.

**Comment by kalaksi** [comment]
Hello! What's the use case? Shouldn't binding to interfaces and ports be controlled with docker?

**Comment by aaabramov** [comment]
Hi @kalaksi,

The use case for specifying ports is pretty straightforward. While you can obviously forward any port you want to the container, sometimes it's more convenient to have both forwarding and target proxy aligned. Let's say when deploying the image to k8s, I prefer to set both ports to 80 or 8080 and name the port accordingly.

In regards to `Listen`, it's a little bit harder for me to come up with a use case.

But my point is that the image already allows you to configure _tinyproxy_ very easily (thanks for that!) and it would be nice to get even more configurable options.

**Comment by kalaksi** [comment]
Okay, I can see the need for Port, but I wouldn't add anything extra that doesn't serve a clear purpose. Other than that, I'll happily accept your contribution.

**Comment by kalaksi** [comment]
Thanks!
