### ISSUE TITLE
 ERROR: Syntax error on line 326

### ISSUE THREAD

**Issue by dr41d45** [kalaksi/docker-tinyproxy#5]
why i get this in CLI after `docker-compose up`? 

> **Warning**
> Attaching to docker-tinyproxy-tinyproxy-1
> docker-tinyproxy-tinyproxy-1  | ERROR: Syntax error on line 326

**Comment by kalaksi** [comment]
There's probably something wrong in your tinyproxy configuration file?
I tested that the default configuration works so maybe you are using a custom config?

**Comment by leobaldoneto** [comment]
I had that same problem when using AUTH_PASSWORD environment with an "&" in the string.

**Comment by leobaldoneto** [comment]
https://github.com/kalaksi/docker-tinyproxy/commit/c64214dd77c4aa689b07e3ea85fb35c67f76da51

# Password for BasicAuth (letters and digits only)

That's an comment in the commit. I think we can just add that comment to the docker-compose.yaml.

**Comment by kalaksi** [comment]
I think you might have had a different issue. At least with just using the environment vars, the password syntax error comes from line 206. It's a good idea to add some more comments to docker-compose.yml, though, so I did.
