### ISSUE TITLE
Please add BasicAuth env variable support

### ISSUE THREAD

**Issue by denis-domanskii** [kalaksi/docker-tinyproxy#7]
Thank you for the project! 

I think it will be important to add BasicAuth env variable. Yes, it's possible to setup it via the mounted config file, but BasicAuth is a mandatory thing because the web proxy can be accessed by anyone on the web, which can be easily abused and is very dangerous.

BasicAuth description: https://tinyproxy.github.io/#BasicAuth

**Comment by kalaksi** [comment]
Yeah, that's a good idea. Changes seem good. I'll test it a bit later and merge after that.

**Comment by kalaksi** [comment]
Thanks for the contribution!
I also added support for secrets-files.
